name: 'Pull Request Name Enforcer'
description: 'github action for enforcing regex matching name on PR'
branding:
  icon: 'book-open'  
  color: 'yellow'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  regex:
    description: 'The regex'
    required: true
  regex-flags:
    description: 'Optional regex flags'
    required: false
    
runs:
  using: 'node12'
  main: 'dist/index.js'